use failure::Error;

#[tokio::main]
async fn main() -> Result<(), Error> {
    // init postgres

    // init accounts service
}
